import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { parseYarnLock } from "../src/lockfile.js";

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/pkg@^1.0.0", "@scope/pkg@^1.2.0":
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.2.3.tgz#abc"
  integrity sha512-SCOPEHASH==

lodash@^4.17.0, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"
  integrity sha512-LODASHHASH==
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard

"@scope/pkg@npm:^1.0.0":
  version: 1.2.3
  resolution: "@scope/pkg@npm:1.2.3"
  checksum: 10c0/bbb
  languageName: node
  linkType: hard
`;

describe("parseYarnLock — v1", () => {
  test("parses name/version/integrity, scoped names, deduped + sorted", () => {
    const coords = parseYarnLock(YARN_V1);
    assert.deepEqual(coords, [
      { name: "@scope/pkg", version: "1.2.3", integrity: "sha512-SCOPEHASH==" },
      { name: "lodash", version: "4.17.21", integrity: "sha512-LODASHHASH==" },
    ]);
  });
});

describe("parseYarnLock — berry (YAML)", () => {
  test("parses name/version from npm: resolution; no SRI (checksum is not integrity)", () => {
    const coords = parseYarnLock(YARN_BERRY);
    assert.deepEqual(coords, [
      { name: "@scope/pkg", version: "1.2.3" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });
});
